### ISSUE TITLE
Connection fails when uptime few days

### ISSUE THREAD

**Issue by VitaliyR** [Naltox/telegram-node-bot#110]
Hello there!

Bot hangs up in few days, throwing next logs.

Can I somehow catch it and reconnect again? 

```
[error]
No network connection. Error: Error: getaddrinfo ENOTFOUND api.telegram.org api.telegram.org:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
request TelegramApiRequest {
  _method: 'getUpdates',
  _params: { timeout: 50, offset: 687001302 },
  _multipart: undefined }


[log]
Retry request TelegramApiRequest {
  _method: 'getUpdates',
  _params: { timeout: 50, offset: 687001302 },
  _multipart: undefined }


[error]
api request error: Body: undefined
Error: SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.response.on.e (/var/www/fspls_bot/node_modules/tiny_request/lib/network.js:68:38)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by LBreda** [comment]
https://github.com/Naltox/telegram-node-bot/issues/101

(tl;dr: not really solved, but updating to the last Node.js version helps)

**Comment by bidadh** [comment]
+1

**Comment by bidadh** [comment]
+1
Actually its not even few days! its few hours.

node version is 6.4.0

**Comment by VitaliyR** [comment]
@bidadh 👍  indeed. Few hours and dead end. No errors, no anything, just lost connection and that's it.

**Comment by dotcypress** [comment]
@bidadh @VitaliyR try something mature :)

https://github.com/telegraf/telegraf
https://github.com/yagop/node-telegram-bot-api

**Comment by Naltox** [comment]
lets move to #101
