### ISSUE TITLE
Network error: Error: getaddrinfo ENOTFOUND api.telegram.org api.telegram.org:443

### ISSUE THREAD

**Issue by chiu0602** [Naltox/telegram-node-bot#134]
After launching the bot for long time, the bot have no response and error message is found on web view (port 7777)

```
08:00:22 [log] - Telegram Master started, 4 CPUs found, 1 workers will start
08:00:22 [log] - WebAdmin  started at 0.0.0.0:7777
23:12:42 [log] - Telegram Worker started at 882 PID
23:22:07 [error] - Network error: Error: getaddrinfo ENOTFOUND api.telegram.org api.telegram.org:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)request {
  "_method": "getUpdates",
  "_params": {
    "timeout": 50,
    "offset": 341856518
  }
}
23:22:08 [log] - Retry request {
  "_method": "getUpdates",
  "_params": {
    "timeout": 50,
    "offset": 341856518
  }
}

```

**Comment by Naltox** [comment]
Hey, check out #101 and try to use webhooks.

**Comment by chiu0602** [comment]
I have seen `webhook` on readme "Getting updates" section, but I don't know how to config it.
