### ISSUE TITLE
Need check for 502 error

### ISSUE THREAD

**Issue by dcromster** [Naltox/telegram-node-bot#166]
I think we need check for this situation:

[error]   
api request error: Telegram returned some html instead of json. Body: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

Error: SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.response.on.e (/home/ubuntu/broader/telegram/node_modules/tiny_request/lib/network.js:70:40)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[log]   
Retry request TelegramApiRequest {
  _method: 'getUpdates',
  _params: { timeout: 50, offset: 0 },
  _multipart: undefined }

**Comment by jesusgn90** [comment]
It seems like a telegram internal error. Maybe a error handler p
For general purpose will be fine to fix this
