### ISSUE TITLE
App crashed > 'chat' of undefined

### ISSUE THREAD

**Issue by whooooop** [Naltox/telegram-node-bot#31]
**After I updated my message, there was an error**

/node_modules/telegram-node-bot/lib/telegram.js:532
        if (update.message["chat"]) {

TypeError: Cannot read property 'chat' of undefined
    at Telegram._processCommand (node_modules/telegram-node-bot/lib/telegram.js:532:27)
    at Array.<anonymous> (node_modules/telegram-node-bot/lib/telegram.js:803:22)
    at Immediate.iter [as _onImmediate](node_modules/telegram-node-bot/lib/telegram.js:814:22)
    at processImmediate [as _immediateCallback](timers.js:374:17)

**Comment by Naltox** [comment]
Its already fixed: https://github.com/Naltox/telegram-node-bot/pull/26
