### ISSUE TITLE
Unable to connect - Proxy problem (localization issue = storage)

### ISSUE THREAD

**Issue by cnavigato** [Naltox/telegram-node-bot#81]
chris@dev-OptiPlex-755-1:~/dev/node/telegram-node-bot-3$ node server.js
/home/chris/dev/node/telegram-node-bot-3/node_modules/telegram-node-bot/lib/localization/Ivan.js:41
        return new Proxy(this, locHandler)
                   ^

ReferenceError: Proxy is not defined
    at new Ivan (/home/chris/dev/node/telegram-node-bot-3/node_modules/telegram-node-bot/lib/localization/Ivan.js:41:20)
    at new Telegram (/home/chris/dev/node/telegram-node-bot-3/node_modules/telegram-node-bot/lib/Telegram.js:37:20)
    at Object.<anonymous> (/home/chris/dev/node/telegram-node-bot-3/server.js:10:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

**Comment by cnavigato** [comment]
referenced closed issues
