### ISSUE TITLE
bot doesn't not respond to messages after a network error has occured

### ISSUE THREAD

**Issue by dutu** [Naltox/telegram-node-bot#89]
After a network error occurs (see below the console log) the bot doesn't respond to messages anymore

```
api request error: Body: undefined 
Error: Error: connect ETIMEDOUT 149.154.167.197:443 
    at Object.exports._errnoException (util.js:1007:11) 
    at exports._exceptionWithHostPort (util.js:1030:20) 
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14) 
```

(manual restart of the app was required to restored the functionality)

**Comment by kamikazechaser** [comment]
```
[error]
api request error: Body: undefined
Error: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
    at Object.exports._errnoException (util.js:1007:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

I have the same issue. Bot up time is barely 16 hours.

**Comment by qadir-genetech** [comment]
I am getting this too #91

**Comment by Naltox** [comment]
Just updated module, think that will help
